// examples/vue-ts/src/hooks/use-controls.tsx
import { h, Fragment, ref, inject, provide } from "vue"
import type { Ref } from "vue"
import type { ControlRecord, ControlValue } from "@zag-js-recipes/shared"

const ControlsSymbol = Symbol("use-controls")

function getDefaultValues<T extends ControlRecord>(obj: T) {
  return Object.keys(obj).reduce(
    (acc, key) => ({
      ...acc,
      [key]: obj[key].defaultValue,
    }),
    {} as ControlValue<T>,
  )
}

export function useControls<T extends ControlRecord>(config: T) {
  const defaults = getDefaultValues(config)
  const state = ref(defaults)

  provide(ControlsSymbol, state)

  function useControlsState() {
    return inject<Ref<ControlValue<T>>>(ControlsSymbol)!
  }

  return {
    context: state,
    useControlsState,
    ui: () => {
      const state = useControlsState()
      return (
        <div class="controls-container">
          {Object.keys(config).map((key: keyof ControlValue<T>) => {
            const { type, label = key, options, placeholder, min, max } = (config[key] ?? {}) as any
            switch (type) {
              case "boolean":
                return (
                  <div key={key} class="checkbox">
                    <input
                      data-testid={key}
                      id={label}
                      type="checkbox"
                      checked={state.value[key] as boolean}
                      onInput={(e) => {
                        //@ts-expect-error
                        state.value[key] = e.currentTarget.checked
                      }}
                    />
                    <label for={label}>{label}</label>
                  </div>
                )
              case "string":
                return (
                  <div key={key} class="text">
                    <label style={{ marginRight: "10px" }}>{label}</label>
                    <input
                      data-testid={key}
                      type="text"
                      placeholder={placeholder}
                      value={state.value[key] as string}
                      onKeydown={(event) => {
                        if (event.key === "Enter") {
                          //@ts-expect-error
                          state.value[key] = (event.target as HTMLInputElement).value
                        }
                      }}
                    />
                  </div>
                )
              case "select":
                return (
                  <div key={key} class="text">
                    <label for={label} style={{ marginRight: "10px" }}>
                      {label}
                    </label>
                    <select
                      data-testid={key}
                      id={label}
                      value={state.value[key] as string}
                      onChange={(e) => {
                        //@ts-expect-error
                        state.value[key] = (e.target as HTMLSelectElement).value
                      }}
                    >
                      <option>-----</option>
                      {options.map((option: any) => (
                        <option key={option} value={option}>
                          {option}
                        </option>
                      ))}
                    </select>
                  </div>
                )
              case "number":
                return (
                  <div key={key} class="text">
                    <label for={label} style={{ marginRight: "10px" }}>
                      {label}
                    </label>
                    <input
                      data-testid={key}
                      id={label}
                      type="number"
                      min={min}
                      max={max}
                      value={state.value[key] as number}
                      onKeydown={(e) => {
                        if (e.key === "Enter") {
                          //@ts-expect-error
                          state.value[key] = (e.target as HTMLInputElement).valueAsNumber
                        }
                      }}
                    />
                  </div>
                )
            }
          })}
        </div>
      )
    },
  }
}

// examples/next-ts/hooks/use-controls.tsx
/* eslint-disable jsx-a11y/no-onchange */
import React, { useState } from "react"
import { ControlRecord, ControlValue } from "@zag-js-recipes/shared"

function getDefaultValues<T extends ControlRecord>(obj: T) {
  return Object.keys(obj).reduce(
    (acc, key) => ({
      ...acc,
      [key]: obj[key].defaultValue,
    }),
    {} as ControlValue<T>,
  )
}

export function useControls<T extends ControlRecord>(config: T) {
  const [state, setState] = useState(getDefaultValues(config))

  return {
    context: state,
    ui: () => (
      <div className="controls-container">
        {Object.keys(config).map((key) => {
          const { type, label = key, options, placeholder, min, max } = (config[key] ?? {}) as any
          switch (type) {
            case "boolean":
              return (
                <div key={key} className="checkbox">
                  <input
                    data-testid={key}
                    id={label}
                    type="checkbox"
                    defaultChecked={state[key] as boolean}
                    onChange={(e) => {
                      setState((s) => ({ ...s, [key]: e.target.checked }))
                    }}
                  />
                  <label htmlFor={label}>{label}</label>
                </div>
              )
            case "string":
              return (
                <div key={key} className="text">
                  <label style={{ marginRight: "10px" }}>{label}</label>
                  <input
                    data-testid={key}
                    type="text"
                    placeholder={placeholder}
                    defaultValue={state[key] as string}
                    onKeyDown={(e) => {
                      if (e.key === "Enter") {
                        setState((s) => ({ ...s, [key]: (e.target as HTMLInputElement).value }))
                      }
                    }}
                  />
                </div>
              )
            case "select":
              return (
                <div key={key} className="text">
                  <label htmlFor={label} style={{ marginRight: "10px" }}>
                    {label}
                  </label>
                  <select
                    data-testid={key}
                    id={label}
                    defaultValue={state[key] as string}
                    onChange={(e) => {
                      setState((s) => ({ ...s, [key]: e.target.value }))
                    }}
                  >
                    <option>-----</option>
                    {options.map((option) => (
                      <option key={option} value={option}>
                        {option}
                      </option>
                    ))}
                  </select>
                </div>
              )
            case "number":
              return (
                <div key={key} className="text">
                  <label htmlFor={label} style={{ marginRight: "10px" }}>
                    {label}
                  </label>
                  <input
                    data-testid={key}
                    id={label}
                    type="number"
                    min={min}
                    max={max}
                    defaultValue={state[key] as number}
                    onKeyDown={(e) => {
                      if (e.key === "Enter") {
                        const val = parseFloat(e.currentTarget.value)
                        setState((s) => ({ ...s, [key]: isNaN(val) ? 0 : val }))
                      }
                    }}
                  />
                </div>
              )
          }
        })}
      </div>
    ),
  }
}
