// examples/vue-ts/src/App.tsx
import { dataAttr } from "@zag-js/dom-utils";
import { routesData } from "@zag-js-recipes/shared";
import { computed, defineComponent } from "vue";
import { RouterLink, RouterView, useRouter } from "vue-router";

const App = defineComponent({
  name: "App",
  setup() {
    const router = useRouter();

    const items = computed(() =>
      routesData.map((route) => {
        const pathname = router.currentRoute.value.path;
        const active = pathname === route.path;
        return (
          <RouterLink
            data-active={dataAttr(active)}
            to={route.path}
            key={route.label}
          >
            {() => route.label}
          </RouterLink>
        );
      })
    );

    return () => (
      <div class="page">
        <aside class="nav">
          <header>Zagjs</header>
          {items.value}
        </aside>
        <RouterView />
      </div>
    );
  },
});

export default App;

// examples/next-ts/pages/_app.tsx
import { dataAttr } from "@zag-js/dom-utils"
import { routesData } from "@zag-js-recipes/shared"
import "@zag-js-recipes/shared/src/style.css"
import { AppProps } from "next/app"
import Head from "next/head"
import Link from "next/link"

export default function App({ Component, pageProps, router }: AppProps) {
  return (
    <div className="page">
      <Head>
        <title>React Machines</title>
      </Head>

      <aside className="nav">
        <header>Zagjs</header>
        {routesData.map((route) => {
          const active = router.pathname === route.path
          return (
            <Link href={route.path} key={route.label} passHref>
              <a data-active={dataAttr(active)}>{route.label}</a>
            </Link>
          )
        })}
      </aside>
      <Component {...pageProps} />
    </div>
  )
}
