// examples/next-ts/pages/_app.tsx
import { dataAttr } from "@zag-js/dom-utils"
import { routesData } from "@zag-js-recipes/shared"
import "@zag-js-recipes/shared/src/style.css"
import { AppProps } from "next/app"
import Head from "next/head"
import Link from "next/link"

export default function App({ Component, pageProps, router }: AppProps) {
  return (
    <div className="page">
      <Head>
        <title>React Machines</title>
      </Head>

      <aside className="nav">
        <header>Zagjs</header>
        {routesData.map((route) => {
          const active = router.pathname === route.path
          return (
            <Link href={route.path} key={route.label} passHref>
              <a data-active={dataAttr(active)}>{route.label}</a>
            </Link>
          )
        })}
      </aside>
      <Component {...pageProps} />
    </div>
  )
}

// examples/solid-ts/src/app.tsx
import { dataAttr } from "@zag-js/dom-utils"
import { routesData } from "@zag-js-recipes/shared"
import { Link, useMatch, useRoutes } from "solid-app-router"
import { Component, For } from "solid-js"
import { routes } from "./routes"
import "../../../shared/src/style.css"

const App: Component = () => {
  const Route = useRoutes(routes)

  return (
    <div class="page">
      <aside class="nav">
        <header>Zagjs</header>
        <For each={routesData} fallback={<div>Loading...</div>}>
          {(route) => {
            const match = useMatch(() => route.path)
            return (
              <Link data-active={dataAttr(!!match())} href={route.path}>
                {route.label}
              </Link>
            )
          }}
        </For>
      </aside>
      <Route />
    </div>
  )
}

export default App
